defaults:
  - original_dataset: ../../dataset/fava-sampling

ents_rels_path: data/entities_relationships/${.original_dataset.name}/response_column/${llm.name}
response_graphs_path: data/graphs/${.original_dataset.name}/sentence/restricted/response_column/response_sentences_column/${llm.name}
samples_graphs_path: data/graphs/${.original_dataset.name}/document/restricted/response_column/samples_column/${llm.name}
fact_prompt_answers_path: data/predict/${.original_dataset.name}/fact_prompt_answers/${llm.name}/${fact_prompt_name}
fact_text_prompt_answers_path: data/predict/${.original_dataset.name}/fact_text_prompt_answers/${llm.name}/${fact_text_prompt_name}
selfcheckgpt_answers_path: data/predict/${.original_dataset.name}/selfcheckgpt_answers/${llm.name}/${selfcheckgpt_prompt_name}
selfcheckgpt_nli_scores_path: data/baselines/selfcheckgpt_nli/${.original_dataset.name}
restricted_by_column: response_column
