defaults:
  - processed_dataset: wiki_bio_sentence_with_prompt_answers
  - llm: api/Llama-3.1-70B-Instruct
  - llm_correction: ../llm/api/gpt-4o
  - prompt: correction/correction_baseline.yaml
  - _self_

predictor: fact_occurrence
fact_prompt_name: fact_prediction_with_inference
fact_text_prompt_name: fact_text_prediction_with_inference
selfcheckgpt_prompt_name: selfcheckgpt-original

llm_correction:
  temperature: 0.5

type: baseline

output_dir: data/correction/correct/${processed_dataset.original_dataset.name}/${type}/${llm.name}/${prompt.name}
